import './App.css';
import React from "react";
import { Total } from './Total';
import { Content } from './Content';
import { Header } from './Header';
import { CoursePart } from './types';

const App: React.FC = () => {
  const courseName = "Half Stack application development";
  const courseParts: CoursePart[] = [
    {
      name: "Fundamentals",
      exerciseCount: 10,
      description: "This is an awesome course part"
    },
    {
      name: "Using props to pass data",
      exerciseCount: 7,
      groupProjectCount: 3
    },
    {
      name: "Deeper type usage",
      exerciseCount: 14,
      description: "Confusing description",
      exerciseSubmissionLink: "https://fake-exercise-submit.made-up-url.dev"
    },
    {
      name: "My Own Course Part",
      exerciseCount: 555,
      description: "Generated by me",
      foo: "bar"
    }
  ];

  const calculateSum = (): number => {
    return courseParts.reduce((carry, part) => carry + part.exerciseCount, 0)
  }

  return (
    <div>
      <Header name={courseName} />
      <Content courseParts={courseParts} />
      <Total sum={calculateSum()} />
    </div>
  )
};

export default App;
